# encoding=utf-8


from unit.excute_ssh import excuteFactory

if __name__ == '__main__':



    tablelist = [
        # 'e3plus-adaptor.sys_std_trade',
        # 'e3plus-adaptor.sys_std_trade_item',
        # 'e3plus-adaptor.sys_std_trade_promotion',
        # 'e3plus-adaptor.sku_inventory_platform_log',
        # 'e3plus-adaptor.hub_api_log',
        'e3plus_trade_integrate.trade_sale_return_bill_settle',
        'e3plus_trade_integrate.trade_sale_return_bill_line',
        'e3plus_trade_integrate.trade_sale_return_bill',
        'e3plus_trade_integrate.trade_sale_check_records',
        'e3plus_trade_integrate.trade_sale_check_bill_goods',
        'e3plus_trade_integrate.trade_sale_bill_settle',
        'e3plus_trade_integrate.trade_sale_bill_line',
        'e3plus_trade_integrate.trade_sale_bill',
        'e3plus_trade_integrate.trade_retail_return_bill_shipment_info',
        'e3plus_trade_integrate.trade_retail_return_bill_line',
        'e3plus_trade_integrate.trade_retail_return_bill',
        'e3plus_trade_integrate.trade_retail_bill_shipment_info',
        'e3plus_trade_integrate.trade_retail_bill_line',
        'e3plus_trade_integrate.trade_retail_bill_adjust_lines',
        'e3plus_trade_integrate.trade_retail_bill_adjust',
        'e3plus_trade_integrate.trade_retail_bill',
        'e3plus_trade_integrate.trade_reconciliation_bs_type_detail',
        'e3plus_trade_integrate.trade_purchase_bill',
        'e3plus_trade_integrate.trade_goods_size_assort_line',
        'e3plus_trade_integrate.trade_fund_check_records',
        'e3plus_system_integrate.sys_staff',
        'e3plus_system_integrate.sys_parameters',
        'e3plus_system_integrate.sys_dict_detail',
        'e3plus_system_integrate.sys_dept',
        'e3plus_stock_integrate.stock_transaction_class',
        'e3plus_stock_integrate.stk_warehouse_group',
        'e3plus_stock_integrate.stk_virtual_warehouse_workflow',
        'e3plus_stock_integrate.stk_virtual_warehouse',
        'e3plus_stock_integrate.stk_stock_physical_workflow',
        'e3plus_stock_integrate.stk_stock_period_summary',
        'e3plus_stock_integrate.stk_stock_logic_workflow',
        'e3plus_stock_integrate.stk_stock_logic_account',
        'e3plus_stock_integrate.stk_serialno_account',
        'e3plus_stock_integrate.stk_goods_size_assort_line',
        'e3plus_stock_integrate.stk_assembly_disassembly_detail',
        'e3plus_stock_integrate.stk_assembly_disassembly_child_detail',
        'e3plus_stock_integrate.stk_assembly_disassembly',
        'e3plus_stock_integrate.stk_allocate_out_bill',
        'e3plus_stock_integrate.stk_allocate_in_bill',
        'e3plus_settlement_integrate.settlement_so_line',
        'e3plus_settlement_integrate.settlement_so_bill',
        'e3plus_settlement_integrate.settlement_retail_shipment_lines',
        'e3plus_settlement_integrate.settlement_retail_bill',
        'e3plus_scm_integrate.scm_goods_size_assort_line',
        'e3plus_scm_integrate.scm_consignee_in_bill',
        'e3plus_order_integrate.ord_retail_return_gds_de',
        'e3plus_order_integrate.ord_retail_return_bill',
        'e3plus_price_integrate.mkt_sale_price_adjust_goods',
        'e3plus_price_integrate.mkt_sale_price_adjust_customer',
        'e3plus_price_integrate.mkt_sale_price_adjust_bill',
        'e3plus_price_integrate.mkt_sale_goods_detail',
        'e3plus_price_integrate.mkt_sale_customer_detail',
        'e3plus_price_integrate.mkt_price_regulation',
        'e3plus_price_integrate.mkt_price_control',
        'e3plus_goods_integrate.gds_sku_extend_attribute',
        'e3plus_goods_integrate.gds_sku_base_attribute',
        'e3plus_goods_integrate.gds_singlproduct',
        'e3plus_goods_integrate.gds_measu_unit',
        'e3plus_goods_integrate.gds_goods_extend_attribute',
        'e3plus_goods_integrate.gds_goods_base_attribute',
        'e3plus_goods_integrate.gds_goods',
        'e3plus_goods_integrate.gds_classification',
        'e3plus_goods_integrate.gds_category_tree',
        'e3plus_goods_integrate.gds_barcode',
        'e3plus_goods_integrate.gds_attrvalue',
        'e3plus_goods_integrate.gds_attribute_group',
        'e3plus_goods_integrate.gds_attribute',
        'e3plus_finance_integrate.fin_stock_period_summary',
        'e3plus_drp_integrate.drp_goods_size_assort_line',
        'e3plus_drp_integrate.drp_cons_sale_bill_line',
        'e3plus_drp_integrate.drp_cons_sale_bill',
        'e3plus_stock_integrate.cst_pac_item_costs_summary',
        'e3plus_stock_integrate.cst_pac_item_costs',
        'e3plus_support_integrate.bas_supplier',
        'e3plus_support_integrate.bas_storehouse',
        'e3plus_support_integrate.bas_stock_organization',
        'e3plus_support_integrate.bas_shop_business_info',
        'e3plus_support_integrate.bas_shop',
        'e3plus_support_integrate.bas_sales_item',
        'e3plus_support_integrate.bas_platform',
        'e3plus_support_integrate.bas_physical_warehouse',
        'e3plus_support_integrate.bas_physical_storage',
        'e3plus_support_integrate.bas_master_data_ext_attribute',
        'e3plus_support_integrate.bas_logic_whareatype',
        'e3plus_support_integrate.bas_logic_warehouse',
        'e3plus_support_integrate.bas_legal_person_company',
        'e3plus_support_integrate.bas_legal_person',
        'e3plus_support_integrate.bas_group_company',
        'e3plus_support_integrate.bas_discount',
        'e3plus_support_integrate.bas_customer_coop_info',
        'e3plus_support_integrate.bas_customer',
        'e3plus_support_integrate.bas_currency',
        'e3plus_support_integrate.bas_cost_center',
        'e3plus_support_integrate.bas_channel',
        'e3plus_support_integrate.bas_business_type',
        'e3plus_support_integrate.bas_brand',
        'e3plus_support_integrate.bas_attribute_value',
        'e3plus_support_integrate.bas_attribute',
        'e3plus_support_integrate.bas_area',
        'e3plus_support_integrate.bas_accounting_company',
        'e3plus_goods_integrate.gds_goods_size_assort'

    ]
    connConfig = {
        'sourceType': 'mysql',
        'sourceUser': 'root',
        'sourcePassword': 'Baison@123',
        'sourceHost': '127.0.0.1',
        'sourcePort': 3306,
        'targetUser': 'default',
        'targetPassword': 'Data123456!',
        'targetHost': '127.0.0.1',
        'targetTcpPort': 9000,
        'targetJdbcPort': 8123,
        'targetDb': 'cdm_real',
        'targetPre': 'ods_',
        'etlType': 'flink',
        'token':'7bb1c3a0f27379bc77a74ef0a0f49bc4',
        'apiHost':'120.55.170.92',
        'apiPort':12345,
        'tenantCode':'root',
        'projectName':'DATAMAX-ETL',
        'processName':'CDM工作流_TM',
        'ssh_address_or_host':'39.108.165.20',
        'ssh_username':'root',
        'ssh_password':'2023<nu?hBsYJs`)S&R^Iq023',
        'remote_bind_address':'172.28.2.12'
    }
    excute=excuteFactory(connConfig)
    jsonContext, sqllist = excute.excute(tablelist)
    # excute.excuteDS(connConfig, jsonContext)
