# encoding=utf-8

from unit import excute
from unit.excute import excuteFactory
import sys
sys.path.append('../')
if __name__ == '__main__':
    tablelist = [
        # 'e3plus-support-integrate-new.bas_discount',
        # 'e3plus-price-integrate-new.mkt_sale_goods_detail',
        # 'e3plus-price-integrate-new.mkt_sale_customer_detail'
        # 'e3plus-support-integrate-new.bas_sales_item'
        # , 'e3plus-trade-integrate-new.trade_reconciliation_bs_type_detail'
        # 'e3plus-support-integrate-new.bas_attribute'
        # 'e3plus-goods-integrate-new.gds_attribute_group'
        # 'e3plus-goods-integrate-new.gds_attribute'
        # 'e3plus-trade-integrate-new.trade_goods_size_assort_line',
        # 'e3plus-trade-integrate-new.trade_purchase_bill',
        # 'e3plus-scm-integrate-new.scm_goods_size_assort_line',
        # 'e3plus-scm-integrate-new.scm_consignee_in_bill',
        # 'e3plus-stock-integrate-new.stk_goods_size_assort_line',
        # 'e3plus-stock-integrate-new.stk_allocate_out_bill',
        # 'e3plus-drp-integrate-new.drp_goods_size_assort_line',
        # 'e3plus-stock-integrate-new.stk_allocate_in_bill'
        # 'e3plus-goods-integrate-new.gds_goods_size_assort'
        # 'e3plus-support-integrate-new.bas_address',
        # 'e3plus-support-integrate-new.bas_address_purpose'
        # 'e3plus-support-integrate-new.bas_contact'
        # 'e3plus-support-integrate-new.bas_shop_business_info'
        # 'e3plus-scm-integrate-new.scm_pur_order_bill',
        # 'e3plus-scm-integrate-new.scm_pur_order_bill_goods',
        # 'e3plus-trade-integrate-new.trade_purchase_bill_detail',
        # 'e3plus-drp-integrate-new.drp_shipment_bill',
        # 'e3plus-drp-integrate-new.drp_shipment_bill_line',
        # 'e3plus-wms-integrate-new.wms_stock_pre_in_bill',
        # 'e3plus-wms-integrate-new.wms_stock_preinbill_goods',
        # 'e3plus-scm-integrate-new.scm_consignee_in_bill_goods',
        # 'e3plus-drp-integrate-new.drp_sale_order_bill',
        # 'e3plus-drp-integrate-new.drp_sale_order_bill_line'
        # 'e3plus_support_integrate.bas_purchasing_meeting'
        'e3plus_trade_uat.trade_sale_return_bill_settle',
        'e3plus_trade_uat.trade_sale_return_bill_line',
        'e3plus_trade_uat.trade_sale_return_bill',
        'e3plus_trade_uat.trade_sale_check_records',
        'e3plus_trade_uat.trade_sale_check_bill_goods',
        'e3plus_trade_uat.trade_sale_bill_settle',
        'e3plus_trade_uat.trade_sale_bill_line',
        'e3plus_trade_uat.trade_sale_bill',
        'e3plus_trade_uat.trade_retail_return_bill_shipment_info',
        'e3plus_trade_uat.trade_retail_return_bill_line',
        'e3plus_trade_uat.trade_retail_return_bill',
        'e3plus_trade_uat.trade_retail_bill_shipment_info',
        'e3plus_trade_uat.trade_retail_bill_line',
        'e3plus_trade_uat.trade_retail_bill_adjust_lines',
        'e3plus_trade_uat.trade_retail_bill_adjust',
        'e3plus_trade_uat.trade_retail_bill',
        'e3plus_trade_uat.trade_reconciliation_bs_type_detail',
        'e3plus_trade_uat.trade_purchase_bill',
        'e3plus_trade_uat.trade_goods_size_assort_line',
        'e3plus_trade_uat.trade_fund_check_records',
        'e3plus_system_uat.sys_staff',
        'e3plus_system_uat.sys_parameters',
        'e3plus_system_uat.sys_dict_detail',
        'e3plus_system_uat.sys_dept',
        'e3plus_stock_uat.stock_transaction_class',
        'e3plus_stock_uat.stk_warehouse_group',
        'e3plus_stock_uat.stk_virtual_warehouse_workflow',
        'e3plus_stock_uat.stk_virtual_warehouse',
        'e3plus_stock_uat.stk_stock_physical_workflow',
        'e3plus_stock_uat.stk_stock_period_summary',
        'e3plus_stock_uat.stk_stock_logic_workflow',
        'e3plus_stock_uat.stk_stock_logic_account',
        'e3plus_stock_uat.stk_serialno_account',
        'e3plus_stock_uat.stk_goods_size_assort_line',
        'e3plus_stock_uat.stk_assembly_disassembly_detail',
        'e3plus_stock_uat.stk_assembly_disassembly_child_detail',
        'e3plus_stock_uat.stk_assembly_disassembly',
        'e3plus_stock_uat.stk_allocate_out_bill',
        'e3plus_stock_uat.stk_allocate_in_bill',
        'e3plus_settlement_uat.settlement_so_line',
        'e3plus_settlement_uat.settlement_so_bill',
        'e3plus_settlement_uat.settlement_retail_shipment_lines',
        'e3plus_settlement_uat.settlement_retail_bill',
        'e3plus_scm_uat.scm_goods_size_assort_line',
        'e3plus_scm_uat.scm_consignee_in_bill',
        'e3plus_order_uat.ord_retail_return_gds_de',
        'e3plus_order_uat.ord_retail_return_bill',
        'e3plus_price_uat.mkt_sale_price_adjust_goods',
        'e3plus_price_uat.mkt_sale_price_adjust_customer',
        'e3plus_price_uat.mkt_sale_price_adjust_bill',
        'e3plus_price_uat.mkt_sale_goods_detail',
        'e3plus_price_uat.mkt_sale_customer_detail',
        'e3plus_price_uat.mkt_price_regulation',
        'e3plus_price_uat.mkt_price_control',
        'e3plus_goods_uat.gds_sku_extend_attribute',
        'e3plus_goods_uat.gds_sku_base_attribute',
        'e3plus_goods_uat.gds_singlproduct',
        'e3plus_goods_uat.gds_measu_unit',
        'e3plus_goods_uat.gds_goods_size_assort',
        'e3plus_goods_uat.gds_goods_extend_attribute',
        'e3plus_goods_uat.gds_goods_base_attribute',
        'e3plus_goods_uat.gds_goods',
        'e3plus_goods_uat.gds_classification',
        'e3plus_goods_uat.gds_category_tree',
        'e3plus_goods_uat.gds_barcode',
        'e3plus_goods_uat.gds_attrvalue',
        'e3plus_goods_uat.gds_attribute_group',
        'e3plus_goods_uat.gds_attribute',
        'e3plus_finance_uat.fin_stock_period_summary',
        'e3plus_drp_uat.drp_goods_size_assort_line',
        'e3plus_drp_uat.drp_cons_sale_bill_line',
        'e3plus_drp_uat.drp_cons_sale_bill',
        'e3plus_stock_uat.cst_pac_item_costs_summary',
        'e3plus_stock_uat.cst_pac_item_costs',
        'e3plus_support_uat.bas_supplier',
        'e3plus_support_uat.bas_storehouse',
        'e3plus_support_uat.bas_stock_organization',
        'e3plus_support_uat.bas_shop_business_info',
        'e3plus_support_uat.bas_shop',
        'e3plus_support_uat.bas_sales_item',
        'e3plus_support_uat.bas_platform',
        'e3plus_support_uat.bas_physical_warehouse',
        'e3plus_support_uat.bas_physical_storage',
        'e3plus_support_uat.bas_master_data_ext_attribute',
        'e3plus_support_uat.bas_logic_whareatype',
        'e3plus_support_uat.bas_logic_warehouse',
        'e3plus_support_uat.bas_legal_person_company',
        'e3plus_support_uat.bas_legal_person',
        'e3plus_support_uat.bas_group_company',
        'e3plus_support_uat.bas_discount',
        'e3plus_support_uat.bas_customer_coop_info',
        'e3plus_support_uat.bas_customer',
        'e3plus_support_uat.bas_currency',
        'e3plus_support_uat.bas_cost_center',
        'e3plus_support_uat.bas_channel',
        'e3plus_support_uat.bas_business_type',
        'e3plus_support_uat.bas_brand',
        'e3plus_support_uat.bas_attribute_value',
        'e3plus_support_uat.bas_attribute',
        'e3plus_support_uat.bas_area',
        'e3plus_support_uat.bas_accounting_company',
        'e3plus_support_uat.bas_address',
        'e3plus_support_uat.bas_address_purpose',
        'e3plus_support_uat.bas_adminarea',
        'e3plus_support_uat.bas_contact',
        'e3plus_scm_uat.scm_pur_order_bill',
        'e3plus_scm_uat.scm_pur_order_bill_goods',
        'e3plus_trade_uat.trade_purchase_bill_detail',
        'e3plus_drp_uat.drp_shipment_bill',
        'e3plus_drp_uat.drp_shipment_bill_line',
        'e3plus_wms_uat.wms_stock_pre_in_bill',
        'e3plus_wms_uat.wms_stock_preinbill_goods',
        'e3plus_scm_uat.scm_consignee_in_bill_goods',
        'e3plus_drp_uat.drp_sale_order_bill',
        'e3plus_drp_uat.drp_sale_order_bill_line',
        'e3plus_support_uat.bas_purchasing_meeting',
        'e3plus_wms_uat.wms_stock_out_bill',
        'e3plus_wms_uat.wms_stockoutbill_goods',
        'e3plus_wms_uat.wms_stock_in_bill',
        'e3plus_wms_uat.wms_stockinbill_goods',
        'e3plus_wms_uat.wms_stkph_adjust_bill',
        'e3plus_wms_uat.wms_stkph_adjbill_detail',
        'e3plus_wms_uat.wms_move_loc_bill',
        'e3plus_wms_uat.wms_move_loc_detail_bill',
        'e3plus_wms_uat.wms_warehouse_inside_processing',
        'e3plus_wms_uat.wms_processing_finished_detail',
        'e3plus_wms_uat.wms_processing_finished_material_detail',
        'e3plus_stock_uat.stk_stock_physical_lock_bill',
        'e3plus_stock_uat.stk_stock_physical_lock_bill_detail'

    ]
    connConfig = {
        'sourceType': 'mysql',
        'sourceUser': 'e3plus',
        'sourcePassword': 'Baison@123',
        'sourceHost': '10.7.99.52',
        'sourcePort': 3306,
        'targetUser': 'e3plus',
        'targetPassword': 'BS_Datamax_2023@',
        'targetHost': '10.7.99.127',
        'targetTcpPort': 9000,
        'targetJdbcPort': 8123,
        'targetDb': 'cdm',
        'targetPre': 'ods_',
        'etlType': 'datax',
        'token':'2e5a799c8cb8060e6eb2b42adbaa01eb',
        'apiHost':'10.7.99.127',
        'apiPort':12345,
        'tenantCode':'baison',
        'projectName':'DATAMAX-ETL',
        'processName':'E3plus_CDM工作流_1'
    }
    excute=excuteFactory(connConfig)
    jsonContext, sqllist = excute.excute(tablelist)
    excute.excuteDS(connConfig, jsonContext)
