# encoding=utf-8

from unit import excute
from unit.excute import excuteFactory

if __name__ == '__main__':
    tablelist = [
        # 'e3plus-trade-new-dev.trade_sale_return_bill_settle',
        # 'e3plus-trade-new-dev.trade_sale_return_bill_line',
        # 'e3plus-trade-new-dev.trade_sale_return_bill',
        # 'e3plus-trade-new-dev.trade_sale_check_records',
        # 'e3plus-trade-new-dev.trade_sale_check_bill_goods',
        # 'e3plus-trade-new-dev.trade_sale_bill_settle',
        # 'e3plus-trade-new-dev.trade_sale_bill_line',
        # 'e3plus-trade-new-dev.trade_sale_bill',
        # 'e3plus-trade-new-dev.trade_retail_return_bill_shipment_info',
        # 'e3plus-trade-new-dev.trade_retail_return_bill_line',
        # 'e3plus-trade-new-dev.trade_retail_return_bill',
        # 'e3plus-trade-new-dev.trade_retail_bill_shipment_info',
        # 'e3plus-trade-new-dev.trade_retail_bill_line',
        # 'e3plus-trade-new-dev.trade_retail_bill_adjust_lines',
        # 'e3plus-trade-new-dev.trade_retail_bill_adjust',
        # 'e3plus-trade-new-dev.trade_retail_bill',
        # 'e3plus-system-new-dev.sys_staff',
        # 'e3plus-system-new-dev.sys_parameters',
        # 'e3plus-system-new-dev.sys_dict_detail',
        # 'e3plus-system-new-dev.sys_dept',
        # 'e3plus-stock-new-dev.stock_transaction_class',
        # 'e3plus-stock-new-dev.stk_warehouse_group',
        # 'e3plus-stock-new-dev.stk_virtual_warehouse_workflow',
        # 'e3plus-stock-new-dev.stk_virtual_warehouse',
        # 'e3plus-stock-new-dev.stk_stock_physical_workflow',
        # 'e3plus-stock-new-dev.stk_stock_period_summary',
        # 'e3plus-stock-new-dev.stk_stock_logic_workflow',
        # 'e3plus-stock-new-dev.stk_stock_logic_account',
        # 'e3plus-stock-new-dev.stk_serialno_account',
        # 'e3plus-stock-new-dev.stk_assembly_disassembly_detail',
        # 'e3plus-stock-new-dev.stk_assembly_disassembly_child_detail',
        # 'e3plus-stock-new-dev.stk_assembly_disassembly',
        # 'e3plus-settlement-new-dev.settlement_so_line',
        # 'e3plus-settlement-new-dev.settlement_so_bill',
        # 'e3plus-order-new-dev.ord_retail_return_gds_de',
        # 'e3plus-order-new-dev.ord_retail_return_bill',
        # 'e3plus-price-new-dev.mkt_price_regulation',
        # 'e3plus-price-new-dev.mkt_price_control',
        # 'e3plus-goods-new-dev.gds_sku_extend_attribute',
        # 'e3plus-goods-new-dev.gds_sku_base_attribute',
        # 'e3plus-goods-new-dev.gds_singlproduct',
        # 'e3plus-goods-new-dev.gds_measu_unit',
        # 'e3plus-goods-new-dev.gds_goods_extend_attribute',
        # 'e3plus-goods-new-dev.gds_goods_base_attribute',
        # 'e3plus-goods-new-dev.gds_goods',
        # 'e3plus-goods-new-dev.gds_classification',
        # 'e3plus-goods-new-dev.gds_category_tree',
        # 'e3plus-goods-new-dev.gds_barcode',
        # 'e3plus-goods-new-dev.gds_attrvalue',
        # 'e3plus-finance-new-dev.fin_stock_period_summary',
        # 'e3plus-drp-new-dev.drp_cons_sale_bill_line',
        # 'e3plus-drp-new-dev.drp_cons_sale_bill',
        # 'e3plus-stock-new-dev.cst_pac_item_costs_summary',
        # 'e3plus-stock-new-dev.cst_pac_item_costs',
        # 'e3plus-support-new-dev.bas_storehouse',
        # 'e3plus-support-new-dev.bas_stock_organization',
        # 'e3plus-support-new-dev.bas_shop_business_info',
        # 'e3plus-support-new-dev.bas_shop',
        # 'e3plus-support-new-dev.bas_platform',
        # 'e3plus-support-new-dev.bas_physical_warehouse',
        # 'e3plus-support-new-dev.bas_physical_storage',
        # 'e3plus-support-new-dev.bas_logic_whareatype',
        # 'e3plus-support-new-dev.bas_logic_warehouse',
        # 'e3plus-support-new-dev.bas_legal_person_company',
        # 'e3plus-support-new-dev.bas_legal_person',
        # 'e3plus-support-new-dev.bas_group_company',
        # 'e3plus-support-new-dev.bas_customer_coop_info',
        # 'e3plus-support-new-dev.bas_customer',
        # 'e3plus-support-new-dev.bas_currency',
        # 'e3plus-support-new-dev.bas_cost_center',
        # 'e3plus-support-new-dev.bas_channel',
        # 'e3plus-support-new-dev.bas_business_type',
        # 'e3plus-support-new-dev.bas_brand',
        # 'e3plus-support-new-dev.bas_area',
        # 'e3plus-support-new-dev.bas_accounting_company',
        # 'e3plus-support-new-dev.bas_supplier',
        # 'e3plus-support-new-dev.bas_attribute_value',
        # 'e3plus-support-new-dev.bas_master_data_ext_attribute',
        # 'e3plus-settlement-new-dev.settlement_retail_bill',
        # 'e3plus-settlement-new-dev.settlement_retail_shipment_lines',
        # 'e3plus-trade-new-dev.trade_fund_check_records'
        # 'e3plus-price-new-dev.mkt_sale_price_adjust_bill',
        # 'e3plus-price-new-dev.mkt_sale_price_adjust_goods',
        # 'e3plus-price-new-dev.mkt_sale_price_adjust_customer'
        # 'e3plus-support-new-dev.bas_discount',
        # 'e3plus-price-new-dev.mkt_sale_goods_detail',
        # 'e3plus-price-new-dev.mkt_sale_customer_detail'
        'icrm_hgr.crm_consume_detail',
        'icrm_hgr.crm_consume',
        'icrm_hgr.base_brand'

    ]
    connConfig = {
        'sourceType': 'mysql',
        'sourceUser': 'root',
        'sourcePassword': 'Data123456!',
        'sourceHost': '192.168.149.94',
        # 'sourceUser': 'root',
        # 'sourcePassword': 'Data123456!',
        # 'sourceHost': '192.168.149.94',
        'sourcePort': 3306,
        'targetUser': 'default',
        'targetPassword': 'Data123456!',
        'targetHost': '192.168.149.32',
        'targetTcpPort': 9020,
        'targetJdbcPort': 8123,
        'targetDb': 'cdm',
        'targetPre': 'ods_',
        'etlType': 'flink',
        'token':'0f3345676bd78c376ab94aa035b1b87b',
        'apiHost':'192.168.149.229',
        'apiPort':12345,
        'tenantCode':'root',
        'projectName':'DATAMAX-ETL',
        'processName':'E3plus_Flink'
    }
    excute=excuteFactory(connConfig)
    jsonContext, sqllist = excute.excute(tablelist)
    # excute.excuteDS(connConfig, jsonContext)
